import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
	en: {
		typeGameId: 'Type your game ID',
		checkGameId: 'Check Game ID again',
		play: 'Play',
		checking: 'Checking...',
		checkGameIdHep: 'Enter the displayed number or ask your teacher what to do.',
		typeName: 'Type your real name',
		checkName: 'You missed your real name.',
		typeNick: 'Type your nickname for the game',
		checkNick: 'You missed your nickname.',
		welcome: 'Welcome to GameQuiz',
		facebookLogin: 'Login with Facebook',
		googleLogin: 'Login with Google',
		joinGameQuiz: 'Join to GameQuiz',
		wannaJoin: 'Do you want to join?',
		confirm: 'Confirm',
		start: 'Start',
		edit: 'Edit',
		delete: 'Delete',
		newQuiz: 'New Quiz',
		quizList: 'Quiz List',
		feedBackList: 'Feedback List',
		student: 'Student',
		wrongCount: 'Wrong Count',
		quizEdit: 'Quiz Edit',
		quizName: 'Quiz Name',
		titleError: '* You have to enter the title',
		questionList: 'Question List',
		newQuestion: 'New Question',
		save: 'Save',
		cancel: 'Cancel',
		questionEdit: 'Question Edit',
		addNewCategory: 'Add new category',
		title: 'Title',
		inputTitle: 'input Title',
		questionTitleError: '* You have to enter the title',
		timeOut: 'Time Out',
		inputTimeOut: 'input Time Out',
		imageUploadHelp: 'Try dropping some files here, or click to select files to upload.',
		example1: 'Example 1',
		example2: 'Example 2',
		example3: 'Example 3',
		example4: 'Example 4',
		answer1: 'Answer 1',
		answer2: 'Answer 2',
		answer3: 'Answer 3',
		answer4: 'Answer 4',
		exampleError: '* You have to enter the all examples',
		answerError: '* You have to choose the answer',
		waitGame: 'Wait your game',
		joinWith: 'Join with',
		mode: 'mode',
		myGameQuiz: 'My GameQuiz',
		selectGameMode: 'Select Game Mode',
		marathon: 'Marathon',
		marathonHelp: 'Who can get the best score to the last?',
		survival: 'Survival',
		survivalHelp: 'Who is the last one?',
		team: 'Team',
		teamHelp: 'Which team is the best?',
		readyToGo: 'Ready to go!',
		getBusy: 'Let\'s get busy',
		answerIs: 'The answer is',
		choseTheExample: 'people(s) chose the example',
		leaderBoard: 'Leader Board',
		scoreis: 'The score is.....',
		ranking: 'Ranking',
		nickName: 'NickName',
		score: 'Score',
		nextQuestion: 'Next Question',
		endOfPlay: 'End of Play',
		goodJob: 'Good job!',
		home: 'Home',
		gameOver: 'Game Over',
		wait: 'WAIT',
		result: 'RESULT'
	},
	ko:{
		typeGameId: '게임 번호를 입력하세요',
		checkGameId: '게임 번호를 다시 확인해주세요',
		play: '시작',
		checking: '확인중...',
		checkGameIdHep: '화면에 표시된 게임 번호를 입력하거나, 선생님께 문의하세요.',
		typeName: '본인 이름을 입력하세요',
		checkName: '이름을 입력해주세요.',
		typeNick: '게임에 표시될 별명을 입력하세요',
		checkNick: '별명을 입력해주세요.',
		welcome: '게임퀴즈에 오신 것을 환영합니다',
		facebookLogin: '페이스북 아이디로 로그인',
		googleLogin: '구글 아이디로 로그인',
		joinGameQuiz: '게임퀴즈에 가입하기',
		wannaJoin: '게임퀴즈에 가입하시겠습니까?',
		confirm: '확인',
		start: '시작',
		edit: '편집',
		delete: '삭제',
		newQuiz: '새로운 퀴즈',
		quizList: '퀴즈 리스트',
		feedBackList: '피드백 리스트',
		student: '학생',
		wrongCount: '틀린 갯수',
		quizEdit: '퀴즈 편집',
		quizName: '퀴즈 이름',
		titleError: '* 퀴즈 이름을 확인 해주세요',
		questionList: '문제 리스트',
		newQuestion: '새로운 문제',
		save: '저장',
		cancel: '취소',
		questionEdit: '문제편집',
		addNewCategory: '카테고리를 입력하세요',
		title: '질문',
		inputTitle: '질문을 입력하세요',
		questionTitleError: '* 질문을 확인 해주세요',
		timeOut: '제한 시간',
		inputTimeOut: '제한 시간을 입력하세요',
		imageUploadHelp: '파일을 끌어서 놓거나, 업로드 파일을 선택하기 위해서 클릭하세요.',
		example1: '보기 1',
		example2: '보기 2',
		example3: '보기 3',
		example4: '보기 4',
		answer1: '정답 1',
		answer2: '정답 2',
		answer3: '정답 3',
		answer4: '정답 4',
		exampleError: '* 모든 보기를 확인 해주세요.',
		answerError: '* 정답을 확인 해주세요.',
		waitGame: '게임을 기다리세요.',
		joinWith: '아래의 번호로 게임에 접속하세요.',
		mode: '모드',
		myGameQuiz: '나의 게임퀴즈',
		selectGameMode: '게임 모드 선택',
		marathon: '마라톤',
		marathonHelp: '마지막에 점수가 가장 높은 사람은 누구일까요?',
		survival: '서바이벌',
		survivalHelp: '최후의 한 사람은 누가 될까요?',
		team: '팀',
		teamHelp: '최고의 팀은 어떤 팀일까요?',
		readyToGo: '준비하세요!',
		getBusy: '달려볼까요?',
		answerIs: '정답은',
		choseTheExample: '명은 선택했습니다',
		leaderBoard: '순위',
		scoreis: '점수는.....',
		ranking: '순위',
		nickName: '별명',
		score: '점수',
		endOfPlay: 'End of Play',
		goodJob: '잘하셨습니다.',
		home: '홈',
		gameOver: '게임이 종료되었습니다.',
		wait: '기다리세요',
		result: '정답을 확인하세요'
	}
});

export default strings
